name: RegionGuard
main: timberman.RegionGuard.RegionGuard
authors: ['Timber1981']
version: 0.5.1 preDev
description: Timberman.de WorldGuard Extension
commands:
  regionguard:
    description: RegionGuard commands
    usage: /<command>
    aliases: regu
  land:
    description: land protection commands
    usage: /<command>